#default: &default
#  adapter: mysql2
#  encoding: utf8
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: my_username
#  password: my_password
#  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: my_username
  password: my_password
  database: myapp_development

test:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: my_username
  password: my_password
  database: myapp_test

production:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: myapp_production
  username: my_production_username
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
